import keyboardStyle from './Keyboard.module.css';

const keys = [
  {
    note: 'C',
    class: keyboardStyle.white,
    alias: 'B#',
    isWhite: true,
    sharpAlteration: null,
    flatAlteration: 'Dbb',
  },
  {
    note: 'C#',
    class: keyboardStyle.black,
    alias: 'Db',
    isWhite: false,
    sharpAlteration: 'B##',
    flatAlteration: null,
  },
  {
    note: 'D',
    class: `${keyboardStyle.white} ${keyboardStyle.offset}`,
    alias: null,
    isWhite: true,
    sharpAlteration: 'C##',
    flatAlteration: 'Ebb',
  },
  {
    note: 'D#',
    class: keyboardStyle.black,
    alias: 'Eb',
    isWhite: false,
    sharpAlteration: null,
    flatAlteration: 'Fbb',
  },
  {
    note: 'E',
    class: `${keyboardStyle.white} ${keyboardStyle.offset}`,
    alias: 'Fb',
    isWhite: true,
    sharpAlteration: 'D##',
    flatAlteration: null,
  },
  {
    note: 'F',
    class: keyboardStyle.white,
    alias: 'E#',
    isWhite: true,
    sharpAlteration: null,
    flatAlteration: 'Gbb',
  },
  {
    note: 'F#',
    class: keyboardStyle.black,
    alias: 'Gb',
    isWhite: false,
    sharpAlteration: 'E##',
    flatAlteration: null,
  },
  {
    note: 'G',
    class: `${keyboardStyle.white} ${keyboardStyle.offset}`,
    alias: null,
    isWhite: true,
    sharpAlteration: 'F##',
    flatAlteration: 'Abb',
  },
  {
    note: 'G#',
    class: keyboardStyle.black,
    alias: 'Ab',
    isWhite: false,
    sharpAlteration: null,
    flatAlteration: null,
  },
  {
    note: 'A',
    class: `${keyboardStyle.white} ${keyboardStyle.offset}`,
    alias: null,
    isWhite: true,
    sharpAlteration: 'G##',
    flatAlteration: 'Bbb',
  },
  {
    note: 'A#',
    class: keyboardStyle.black,
    alias: 'Bb',
    isWhite: false,
    sharpAlteration: null,
    flatAlteration: 'Cbb',
  },
  {
    note: 'B',
    class: `${keyboardStyle.white} ${keyboardStyle.offset}`,
    alias: 'Cb',
    isWhite: true,
    sharpAlteration: 'A##',
    flatAlteration: null,
  },
];

export default keys;
